/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.2 		*/
/*  Created On : 21-май-2025 12:16:20 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Sequences for Autonumber Columns */

 

 

 

 

DROP SEQUENCE IF EXISTS public.users_tab_num_seq
;

/* Drop Tables */

DROP TABLE IF EXISTS public.approvers CASCADE
;

DROP TABLE IF EXISTS public.pass_statuses CASCADE
;

DROP TABLE IF EXISTS public.pass_types CASCADE
;

DROP TABLE IF EXISTS public.passes CASCADE
;

DROP TABLE IF EXISTS public.status CASCADE
;

DROP TABLE IF EXISTS public.support_request CASCADE
;

DROP TABLE IF EXISTS public.users CASCADE
;

/* Create Tables */

CREATE TABLE public.approvers
(
	id serial NOT NULL,
	pass_id integer NOT NULL,
	fullname text NOT NULL,
	login varchar(255) NOT NULL,
	position text NOT NULL,
	status_id integer NULL
)
;

CREATE TABLE public.pass_statuses
(
	id integer NOT NULL,
	status varchar(255) NOT NULL
)
;

CREATE TABLE public.pass_types
(
	id integer NOT NULL,
	type varchar(255) NOT NULL
)
;

CREATE TABLE public.passes
(
	id serial NOT NULL,
	pass_type integer NULL,
	date_created timestamp with time zone NOT NULL,
	date_modified timestamp with time zone NULL,
	status_id integer NULL,
	author_id integer NULL,
	photo varchar(255) NULL,
	"fullName" text NOT NULL,
	phone text NOT NULL,
	organization text NOT NULL,
	email text NOT NULL,
	"birthDate" date NOT NULL,
	"hasCar" text NOT NULL,
	justification text NOT NULL,
	"startDate" date NOT NULL,
	"endDate" date NOT NULL
)
;

CREATE TABLE public.status
(
	id bigint NOT NULL,
	title varchar(255) NOT NULL,
	slug varchar(255) NOT NULL
)
;

CREATE TABLE public.support_request
(
	id serial NOT NULL,
	user_id integer NOT NULL,
	status_id integer NOT NULL,
	problem varchar(255) NOT NULL,
	email varchar(255) NOT NULL,
	phone_num integer NOT NULL,
	content varchar(255) NOT NULL
)
;

CREATE TABLE public.users
(
	id serial NOT NULL,
	role varchar(255) NOT NULL   DEFAULT 'Пользователь',	-- user | admin или  Пользователь | Администратор
	"tabNum" integer NOT NULL   DEFAULT NEXTVAL(('users_tab_num_seq'::text)::regclass),
	surname varchar(255) NOT NULL,
	name varchar(255) NOT NULL,
	patronymic varchar(255) NOT NULL,
	pos varchar(255) NULL,
	department varchar(255) NULL,
	login varchar(255) NOT NULL,
	email varchar(255) NOT NULL,
	password varchar(255) NOT NULL,
	"phoneNum" varchar(10) NULL,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE public.approvers ADD CONSTRAINT approvers_pkey
	PRIMARY KEY (id)
;

ALTER TABLE public.pass_statuses ADD CONSTRAINT pass_statuses_pkey
	PRIMARY KEY (id)
;

ALTER TABLE public.pass_types ADD CONSTRAINT pass_types_pkey
	PRIMARY KEY (id)
;

ALTER TABLE public.passes ADD CONSTRAINT passes_pkey
	PRIMARY KEY (id)
;

ALTER TABLE public.status ADD CONSTRAINT status_pkey
	PRIMARY KEY (id)
;

ALTER TABLE public.support_request ADD CONSTRAINT support_request_pkey
	PRIMARY KEY (id)
;

ALTER TABLE public.users ADD CONSTRAINT users_pkey
	PRIMARY KEY (id)
;

ALTER TABLE public.users 
  ADD CONSTRAINT users_tabnum_unique UNIQUE ("tabNum")
;

ALTER TABLE public.users 
  ADD CONSTRAINT users_login_key73 UNIQUE (login)
;

ALTER TABLE public.users 
  ADD CONSTRAINT users_login_key71 UNIQUE (login)
;

ALTER TABLE public.users 
  ADD CONSTRAINT users_login_key69 UNIQUE (login)
;

ALTER TABLE public.users 
  ADD CONSTRAINT users_login_key67 UNIQUE (login)
;

ALTER TABLE public.users 
  ADD CONSTRAINT users_login_key11 UNIQUE (login)
;

ALTER TABLE public.users 
  ADD CONSTRAINT users_login_unique UNIQUE (login)
;

ALTER TABLE public.users 
  ADD CONSTRAINT users_login_key21 UNIQUE (login)
;

ALTER TABLE public.users 
  ADD CONSTRAINT users_login_key23 UNIQUE (login)
;

ALTER TABLE public.users 
  ADD CONSTRAINT users_login_key24 UNIQUE (login)
;

ALTER TABLE public.users 
  ADD CONSTRAINT users_login_key25 UNIQUE (login)
;

ALTER TABLE public.users 
  ADD CONSTRAINT users_login_key22 UNIQUE (login)
;

ALTER TABLE public.users 
  ADD CONSTRAINT users_login_key UNIQUE (login)
;

ALTER TABLE public.users 
  ADD CONSTRAINT users_login_key1 UNIQUE (login)
;

ALTER TABLE public.users 
  ADD CONSTRAINT users_login_key2 UNIQUE (login)
;

ALTER TABLE public.users 
  ADD CONSTRAINT users_login_key3 UNIQUE (login)
;

ALTER TABLE public.users 
  ADD CONSTRAINT users_login_key4 UNIQUE (login)
;

ALTER TABLE public.users 
  ADD CONSTRAINT users_login_key5 UNIQUE (login)
;

ALTER TABLE public.users 
  ADD CONSTRAINT users_login_key6 UNIQUE (login)
;

ALTER TABLE public.users 
  ADD CONSTRAINT users_login_key37 UNIQUE (login)
;

ALTER TABLE public.users 
  ADD CONSTRAINT users_login_key38 UNIQUE (login)
;

ALTER TABLE public.users 
  ADD CONSTRAINT users_login_key36 UNIQUE (login)
;

ALTER TABLE public.users 
  ADD CONSTRAINT users_login_key27 UNIQUE (login)
;

ALTER TABLE public.users 
  ADD CONSTRAINT users_login_key29 UNIQUE (login)
;

ALTER TABLE public.users 
  ADD CONSTRAINT users_login_key31 UNIQUE (login)
;

ALTER TABLE public.users 
  ADD CONSTRAINT users_login_key32 UNIQUE (login)
;

ALTER TABLE public.users 
  ADD CONSTRAINT users_login_key34 UNIQUE (login)
;

ALTER TABLE public.users 
  ADD CONSTRAINT users_login_key58 UNIQUE (login)
;

ALTER TABLE public.users 
  ADD CONSTRAINT users_login_key60 UNIQUE (login)
;

ALTER TABLE public.users 
  ADD CONSTRAINT users_login_key62 UNIQUE (login)
;

ALTER TABLE public.users 
  ADD CONSTRAINT users_login_key64 UNIQUE (login)
;

ALTER TABLE public.users 
  ADD CONSTRAINT users_login_key65 UNIQUE (login)
;

ALTER TABLE public.users 
  ADD CONSTRAINT users_login_key66 UNIQUE (login)
;

ALTER TABLE public.users 
  ADD CONSTRAINT users_login_key63 UNIQUE (login)
;

ALTER TABLE public.users 
  ADD CONSTRAINT users_login_key61 UNIQUE (login)
;

ALTER TABLE public.users 
  ADD CONSTRAINT users_login_key59 UNIQUE (login)
;

ALTER TABLE public.users 
  ADD CONSTRAINT users_login_key57 UNIQUE (login)
;

ALTER TABLE public.users 
  ADD CONSTRAINT users_login_key35 UNIQUE (login)
;

ALTER TABLE public.users 
  ADD CONSTRAINT users_login_key33 UNIQUE (login)
;

ALTER TABLE public.users 
  ADD CONSTRAINT users_login_key30 UNIQUE (login)
;

ALTER TABLE public.users 
  ADD CONSTRAINT users_login_key28 UNIQUE (login)
;

ALTER TABLE public.users 
  ADD CONSTRAINT users_login_key26 UNIQUE (login)
;

ALTER TABLE public.users 
  ADD CONSTRAINT users_login_key7 UNIQUE (login)
;

ALTER TABLE public.users 
  ADD CONSTRAINT users_login_key8 UNIQUE (login)
;

ALTER TABLE public.users 
  ADD CONSTRAINT users_login_key9 UNIQUE (login)
;

ALTER TABLE public.users 
  ADD CONSTRAINT users_login_key10 UNIQUE (login)
;

ALTER TABLE public.users 
  ADD CONSTRAINT users_login_key12 UNIQUE (login)
;

ALTER TABLE public.users 
  ADD CONSTRAINT users_login_key13 UNIQUE (login)
;

ALTER TABLE public.users 
  ADD CONSTRAINT users_login_key14 UNIQUE (login)
;

ALTER TABLE public.users 
  ADD CONSTRAINT users_login_key16 UNIQUE (login)
;

ALTER TABLE public.users 
  ADD CONSTRAINT users_login_key18 UNIQUE (login)
;

ALTER TABLE public.users 
  ADD CONSTRAINT users_login_key40 UNIQUE (login)
;

ALTER TABLE public.users 
  ADD CONSTRAINT users_login_key43 UNIQUE (login)
;

ALTER TABLE public.users 
  ADD CONSTRAINT users_login_key44 UNIQUE (login)
;

ALTER TABLE public.users 
  ADD CONSTRAINT users_login_key46 UNIQUE (login)
;

ALTER TABLE public.users 
  ADD CONSTRAINT users_login_key47 UNIQUE (login)
;

ALTER TABLE public.users 
  ADD CONSTRAINT users_login_key49 UNIQUE (login)
;

ALTER TABLE public.users 
  ADD CONSTRAINT users_login_key50 UNIQUE (login)
;

ALTER TABLE public.users 
  ADD CONSTRAINT users_login_key52 UNIQUE (login)
;

ALTER TABLE public.users 
  ADD CONSTRAINT users_login_key54 UNIQUE (login)
;

ALTER TABLE public.users 
  ADD CONSTRAINT users_login_key56 UNIQUE (login)
;

ALTER TABLE public.users 
  ADD CONSTRAINT users_login_key55 UNIQUE (login)
;

ALTER TABLE public.users 
  ADD CONSTRAINT users_login_key53 UNIQUE (login)
;

ALTER TABLE public.users 
  ADD CONSTRAINT users_login_key51 UNIQUE (login)
;

ALTER TABLE public.users 
  ADD CONSTRAINT users_login_key48 UNIQUE (login)
;

ALTER TABLE public.users 
  ADD CONSTRAINT users_login_key45 UNIQUE (login)
;

ALTER TABLE public.users 
  ADD CONSTRAINT users_login_key42 UNIQUE (login)
;

ALTER TABLE public.users 
  ADD CONSTRAINT users_login_key41 UNIQUE (login)
;

ALTER TABLE public.users 
  ADD CONSTRAINT users_login_key39 UNIQUE (login)
;

ALTER TABLE public.users 
  ADD CONSTRAINT users_login_key19 UNIQUE (login)
;

ALTER TABLE public.users 
  ADD CONSTRAINT users_login_key20 UNIQUE (login)
;

ALTER TABLE public.users 
  ADD CONSTRAINT users_login_key17 UNIQUE (login)
;

ALTER TABLE public.users 
  ADD CONSTRAINT users_login_key15 UNIQUE (login)
;

ALTER TABLE public.users 
  ADD CONSTRAINT users_login_key68 UNIQUE (login)
;

ALTER TABLE public.users 
  ADD CONSTRAINT users_login_key70 UNIQUE (login)
;

ALTER TABLE public.users 
  ADD CONSTRAINT users_login_key72 UNIQUE (login)
;

ALTER TABLE public.users 
  ADD CONSTRAINT users_email_key73 UNIQUE (email)
;

ALTER TABLE public.users 
  ADD CONSTRAINT users_email_key71 UNIQUE (email)
;

ALTER TABLE public.users 
  ADD CONSTRAINT users_email_key69 UNIQUE (email)
;

ALTER TABLE public.users 
  ADD CONSTRAINT users_email_key67 UNIQUE (email)
;

ALTER TABLE public.users 
  ADD CONSTRAINT users_email_key39 UNIQUE (email)
;

ALTER TABLE public.users 
  ADD CONSTRAINT users_email_key38 UNIQUE (email)
;

ALTER TABLE public.users 
  ADD CONSTRAINT users_email_key36 UNIQUE (email)
;

ALTER TABLE public.users 
  ADD CONSTRAINT users_email_key35 UNIQUE (email)
;

ALTER TABLE public.users 
  ADD CONSTRAINT users_email_key33 UNIQUE (email)
;

ALTER TABLE public.users 
  ADD CONSTRAINT users_email_key10 UNIQUE (email)
;

ALTER TABLE public.users 
  ADD CONSTRAINT users_email_key16 UNIQUE (email)
;

ALTER TABLE public.users 
  ADD CONSTRAINT users_email_key18 UNIQUE (email)
;

ALTER TABLE public.users 
  ADD CONSTRAINT users_email_key20 UNIQUE (email)
;

ALTER TABLE public.users 
  ADD CONSTRAINT users_email_key52 UNIQUE (email)
;

ALTER TABLE public.users 
  ADD CONSTRAINT users_email_key54 UNIQUE (email)
;

ALTER TABLE public.users 
  ADD CONSTRAINT users_email_key56 UNIQUE (email)
;

ALTER TABLE public.users 
  ADD CONSTRAINT users_email_key58 UNIQUE (email)
;

ALTER TABLE public.users 
  ADD CONSTRAINT users_email_key65 UNIQUE (email)
;

ALTER TABLE public.users 
  ADD CONSTRAINT users_email_key63 UNIQUE (email)
;

ALTER TABLE public.users 
  ADD CONSTRAINT users_email_key59 UNIQUE (email)
;

ALTER TABLE public.users 
  ADD CONSTRAINT users_email_key43 UNIQUE (email)
;

ALTER TABLE public.users 
  ADD CONSTRAINT users_email_key53 UNIQUE (email)
;

ALTER TABLE public.users 
  ADD CONSTRAINT users_email_key51 UNIQUE (email)
;

ALTER TABLE public.users 
  ADD CONSTRAINT users_email_key21 UNIQUE (email)
;

ALTER TABLE public.users 
  ADD CONSTRAINT users_email_key29 UNIQUE (email)
;

ALTER TABLE public.users 
  ADD CONSTRAINT users_email_key31 UNIQUE (email)
;

ALTER TABLE public.users 
  ADD CONSTRAINT users_email_key32 UNIQUE (email)
;

ALTER TABLE public.users 
  ADD CONSTRAINT users_email_key30 UNIQUE (email)
;

ALTER TABLE public.users 
  ADD CONSTRAINT users_email_key23 UNIQUE (email)
;

ALTER TABLE public.users 
  ADD CONSTRAINT users_email_key25 UNIQUE (email)
;

ALTER TABLE public.users 
  ADD CONSTRAINT users_email_key27 UNIQUE (email)
;

ALTER TABLE public.users 
  ADD CONSTRAINT users_email_key28 UNIQUE (email)
;

ALTER TABLE public.users 
  ADD CONSTRAINT users_email_key26 UNIQUE (email)
;

ALTER TABLE public.users 
  ADD CONSTRAINT users_email_key24 UNIQUE (email)
;

ALTER TABLE public.users 
  ADD CONSTRAINT users_email_key22 UNIQUE (email)
;

ALTER TABLE public.users 
  ADD CONSTRAINT users_email_key19 UNIQUE (email)
;

ALTER TABLE public.users 
  ADD CONSTRAINT users_email_key17 UNIQUE (email)
;

ALTER TABLE public.users 
  ADD CONSTRAINT users_email_key12 UNIQUE (email)
;

ALTER TABLE public.users 
  ADD CONSTRAINT users_email_key13 UNIQUE (email)
;

ALTER TABLE public.users 
  ADD CONSTRAINT users_email_key14 UNIQUE (email)
;

ALTER TABLE public.users 
  ADD CONSTRAINT users_email_key44 UNIQUE (email)
;

ALTER TABLE public.users 
  ADD CONSTRAINT users_email_key46 UNIQUE (email)
;

ALTER TABLE public.users 
  ADD CONSTRAINT users_email_key47 UNIQUE (email)
;

ALTER TABLE public.users 
  ADD CONSTRAINT users_email_key45 UNIQUE (email)
;

ALTER TABLE public.users 
  ADD CONSTRAINT users_email_key42 UNIQUE (email)
;

ALTER TABLE public.users 
  ADD CONSTRAINT users_email_key5 UNIQUE (email)
;

ALTER TABLE public.users 
  ADD CONSTRAINT users_email_key6 UNIQUE (email)
;

ALTER TABLE public.users 
  ADD CONSTRAINT users_email_key7 UNIQUE (email)
;

ALTER TABLE public.users 
  ADD CONSTRAINT users_email_key8 UNIQUE (email)
;

ALTER TABLE public.users 
  ADD CONSTRAINT users_email_key9 UNIQUE (email)
;

ALTER TABLE public.users 
  ADD CONSTRAINT users_email_key34 UNIQUE (email)
;

ALTER TABLE public.users 
  ADD CONSTRAINT users_email_key37 UNIQUE (email)
;

ALTER TABLE public.users 
  ADD CONSTRAINT users_email_key40 UNIQUE (email)
;

ALTER TABLE public.users 
  ADD CONSTRAINT users_email_key41 UNIQUE (email)
;

ALTER TABLE public.users 
  ADD CONSTRAINT users_email_key61 UNIQUE (email)
;

ALTER TABLE public.users 
  ADD CONSTRAINT users_email_key1 UNIQUE (email)
;

ALTER TABLE public.users 
  ADD CONSTRAINT users_email_key49 UNIQUE (email)
;

ALTER TABLE public.users 
  ADD CONSTRAINT users_email_key50 UNIQUE (email)
;

ALTER TABLE public.users 
  ADD CONSTRAINT users_email_key48 UNIQUE (email)
;

ALTER TABLE public.users 
  ADD CONSTRAINT users_email_key2 UNIQUE (email)
;

ALTER TABLE public.users 
  ADD CONSTRAINT users_email_key3 UNIQUE (email)
;

ALTER TABLE public.users 
  ADD CONSTRAINT users_email_key4 UNIQUE (email)
;

ALTER TABLE public.users 
  ADD CONSTRAINT users_email_key60 UNIQUE (email)
;

ALTER TABLE public.users 
  ADD CONSTRAINT users_email_key57 UNIQUE (email)
;

ALTER TABLE public.users 
  ADD CONSTRAINT users_email_key55 UNIQUE (email)
;

ALTER TABLE public.users 
  ADD CONSTRAINT users_email_key15 UNIQUE (email)
;

ALTER TABLE public.users 
  ADD CONSTRAINT users_email_key11 UNIQUE (email)
;

ALTER TABLE public.users 
  ADD CONSTRAINT users_email_unique UNIQUE (email)
;

ALTER TABLE public.users 
  ADD CONSTRAINT users_email_key UNIQUE (email)
;

ALTER TABLE public.users 
  ADD CONSTRAINT users_email_key62 UNIQUE (email)
;

ALTER TABLE public.users 
  ADD CONSTRAINT users_email_key64 UNIQUE (email)
;

ALTER TABLE public.users 
  ADD CONSTRAINT users_email_key66 UNIQUE (email)
;

ALTER TABLE public.users 
  ADD CONSTRAINT users_email_key68 UNIQUE (email)
;

ALTER TABLE public.users 
  ADD CONSTRAINT users_email_key70 UNIQUE (email)
;

ALTER TABLE public.users 
  ADD CONSTRAINT users_email_key72 UNIQUE (email)
;

/* Create Foreign Key Constraints */

ALTER TABLE public.approvers ADD CONSTRAINT approvers_pass_id_fkey
	FOREIGN KEY (pass_id) REFERENCES public.passes (id) ON DELETE Cascade ON UPDATE Cascade
;

ALTER TABLE public.approvers ADD CONSTRAINT approvers_status_id_fkey
	FOREIGN KEY (status_id) REFERENCES public.pass_statuses (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE public.support_request ADD CONSTRAINT support_request_user_id_foreign
	FOREIGN KEY (user_id) REFERENCES public.users (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE public.support_request ADD CONSTRAINT support_request_status_id_foreign
	FOREIGN KEY (status_id) REFERENCES public.status (id) ON DELETE No Action ON UPDATE No Action
;

/* Create Table Comments, Sequences for Autonumber Columns */

 

 

 

COMMENT ON COLUMN public.users.role
	IS 'user | admin или 
Пользователь | Администратор'
;

 

CREATE SEQUENCE public.users_tab_num_seq INCREMENT 1 START 1
;
